### PR TITLE
Useful gitignore to lazy ppls

### PR DESCRIPTION
**Pull request by aurdevv**
Add example gitignore for lazy peoples

### CODE REVIEW

**Comment by aurdevv** [comment]
Im dum dum.

**Comment by FrostyTheDumDum** [comment]
I agree with this PR, but there wouldn't be any node js things going around here (i think) so i dont think this is important

**Review by BluemanGaming — APPROVED** [review]

**Comment by aurdevv** [comment]
Merging with Squash is better but whatever

**Comment by nearlySplat** [comment]
Squash is supreme

**Pull request merged**
